# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Demo user
guest = User.create!(username: "Guest", email: "guest@gmail.com", fname: "Guest", city_id: "1", password: "password")

# Cities
houston = City.create!(name: "Houston", state: "TX", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647888/houston1_ltlfdc.jpg")
sf = City.create!(name: "SF / Bay Area", state: "CA", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647889/sanfrancisco1_vysi65.jpg")
nyc = City.create!(name: "New York City", state: "NY", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647889/newyorkcity1_nryrmf.jpg")
miami = City.create!(name: "Miami", state: "FL", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647888/miami1_hbpvyu.jpg")
nashville = City.create!(name: "Nashville", state: "TN", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647892/nashville1_r9zpjh.jpg")
atlanta = City.create!(name: "Atlanta", state: "GA", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647888/atlanta1_tl6emw.jpg")
paris = City.create!(name: "Paris", country: "France", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647889/paris1_zmrbai.jpg")
barcelona = City.create!(name: "Barcelona", country: "Spain", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647891/barcelona1_mnvkhp.jpg")
istanbul = City.create!(name: "Istanbul", country: "Turkey", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647888/istanbul1_ny3pbu.jpg")
dc = City.create!(name: "Washington D.C.", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647892/washingtondc1_mufypj.jpg")
la = City.create!(name: "Los Angeles", state: "CA", country: "USA", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647888/losangeles1_zhzpkl.jpg")
toronto = City.create!(name: "Toronto", country: "Canada", pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478647890/toronto1_ukmauw.jpg")

# profile descriptions
descriptions = ["I was born in Pakistan but moved here after a grand total of 3 months so pretty much brought up here. I'd say 2014 for me was my 'year of travel'. I was lucky enough to spend 3 weeks with people from around the world on a Government of India program in January. During my summer vacation I travelled around Malaysia, Singapore and India again. From then on I became increasingly fascinated by people's stories and experiences. It got to a point where one time I even went up to a random Swiss guy in the streets of Bangalore and said 'How did you end up here?', needless to say, a beautiful friendship (Facebook friends) developed from then on (haha!) So apart from regularly wondering why I chose to study engineering (I'm still somehow surviving), I love exploring, good cake and experiencing different cultures to name a few. This last year I was also part of a team running an organisation called AIESEC at my university (UCSF). I learnt a lot about myself and how as individuals we are able to create a positive impact on others. Sounds deep hah! But basically what stood out were meaningful conversations with like-minded people. And crazily enough I stumbled upon LetsGetCake which carries on doing just that! So that's why LetsGetCake is awesome, you're awesome and let's continue over some nice unhealthy cake (in other words HEAVEN)!",

"I was born and bred in the rolling hills of Yorkshire before moving down here 5 years ago... with a few detours along the way. My day (and sometimes night) job involves supporting charities to grow and increase their impact. I love the outdoors and adventure sports - some of the hobbies I’ve picked up over the years include kitesurfing, mountaineering and parkour. OK, one of those is a lie... Guess which. I make brilliantly terrible (or perhaps terribly brilliant) puns. Having lived in South America, I’ve become a total hispanophile and love discovering pockets of Latin life in SF.",

"I am a social entrepreneur and always interested in finding new ways to solve old problems. I believe that diversity of thought and opinion is of the utmost importance but I also think that we are all united by our common humanity. I enjoy meeting people from all walks of life and all striking up conversations about pretty much anything.",

"I love cake particularly Red Velvet. If you introduce me to a cake I will respond with a disproportionate amount of enthusiasm. I was named after Caleb. I grew up in Maryland just next to Washington DC and came here when I was 12. I studied Social Anthropology at the University of Manchester and last year spent five months working in the Jungle in Ecuador living with an indigenous community and looking at indigenous identity in the face of oil extraction. I love being outside and have worked on farms and selling fruit and vegetables in SF since the age of 14. I’ve been bitten by a Pirana, been chased by a mob of angry miners and now find myself working in the urban jungle that is San Francisco.",

"My story isn't about what I do, where I'm from, or who I work for -- that's not interesting. My story is more about what excites me to my core. I've been blessed/cursed with a bout of wanderlust that I can't seem to shake. Always looking for new places, new faces, new sounds, to satisfy my hunger and to know more about this world. Music simultaneously grounds me and lifts me to transcendental heights. I am forever on a path of self-evolution and I will never pretend that I have it all figured out. Now I want to know, what excites you?",

"People always say – just be you! But I’ve always wondered just which me to bring to the table. Is it the small town cowgirl who grew up learning how to wrangle cows, ride horses and fix anything with duct tape? Or maybe the big city girl who’s always on the hunt for the best ramen in LA and that perfect partner to existentially examine anything and everything with. What about the traveler who will argue the merits of only packing three pairs of underwear, or the homebody who will spend hours obsessing over home decorating magazines? So I give myself permission to be whichever me I am in the moment. We are all dynamic people in a beautiful state of flux – I love to meet people wherever they are on that arc. Which side of your lovely self will emerge over tea?",

"I’m just as confused as the next person and am trying to figure life out by learning from other people’s stories... I like traveling the world to do so but I’m also really looking forward to doing more of that at home in Seattle. I am a Microsoftie by day and for fun I do improv comedy and jam to guitar-friendly songs. I listen to pretty much every type of music, from Katy Perry to Slipknot to Ludovico Einaudi, and think KFC is the greatest thing in the world. Hoomins fascinate me.",

"I’m kind of a mover, (aka I’ve lived in 12 different places) so I’ve gotten really good at saying “Hi, I’m Anshu” to literally everyone I meet. On Sundays I’m usually attempting to do homework while watching football unless it’s the off season, and then there’s baseball/basketball/hockey. My favorite spot on campus is the Arts Annex because not only do I love dancing in the studios but I love creating art for no reason what-so-ever. Three things in the world that I can’t live without are chocolate chip cookies, music, and my younger brother.",

"I'm most in my element when I (almost) can’t breathe because I'm laughing so hard, making others smile and feel good about themselves, embracing the outdoors, running around excitedly taking pictures, and connecting with others...aka YOU. Come join me and I'll tell you more if you'd like! :)",

"As a recovering TED Talks binger, I’ve become fascinated with stories. I love learning about what set people’s hearts on fire and what keeps them up late at night sans caffeine. What inspires me is Steve Job’s commencement speech where I learned to live authentically and unapologetically. I admire those who are unafraid to live courageously in this world and dare greatly. Now, let’s pour the tea!"]


# Hosts
user1 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "1",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user2 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user3 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user4 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user5 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "1",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user6 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user7 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user8 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user9 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "1",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user10 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "1", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user11 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "2",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user12 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user13 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user14 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user15 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "2",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user16 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user17 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user18 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user19 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "2",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user20 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "2", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user21 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "3",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user22 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user23 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user24 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user25 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "3",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user26 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user27 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user28 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user29 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "3",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user30 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "3", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user31 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "4",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user32 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user33 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user34 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user35 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "4",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user36 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user37 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user38 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user39 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "4",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user40 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "4", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user41 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "5",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user42 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user43 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user44 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user45 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "5",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user46 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user47 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user48 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user49 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "5",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user50 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "5", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user51 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "6",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user52 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user53 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user54 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user55 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "6",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user56 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user57 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user58 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user59 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "6",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user60 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "6", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user61 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "7",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user62 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user63 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user64 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user65 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "7",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user66 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user67 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user68 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user69 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "7",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user70 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "7", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user71 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "8",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user72 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user73 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user74 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user75 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "8",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user76 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user77 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user78 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user79 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "8",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user80 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "8", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user81 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "9",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user82 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user83 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user84 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user85 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "9",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user86 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user87 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user88 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user89 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "9",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user80 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "9", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user91 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "11",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user92 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user93 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user94 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user95 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "11",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user96 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user97 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user98 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user99 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "11",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user100 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "11", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])

user101 = User.create!(username: "Humza", email: "humzacodemail@gmail.com", fname: "Humza", lname: "Baig", city_id: "12",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Humza_t3uyph.jpg", profile: descriptions[1])
user102 = User.create!(username: "Eric", email: "kwokcity@gmail.com", fname: "Eric", lname: "Kwok", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Eric_bplddj.jpg", profile: descriptions[2])
user103 = User.create!(username: "Can", email: "canlekili@gmail.com", fname: "Can", lname: "Lekili", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905353/Can_sgzo3g.jpg", profile: descriptions[3])
user104 = User.create!(username: "Caleb", email: "calebontivaros@gmail.com", fname: "Caleb", lname: "Ontivaros", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905354/Caleb_shculr.jpg", profile: descriptions[4])
user105 = User.create!(username: "Jenn", email: "jenngeorge@gmail.com", fname: "Jennifer", lname: "George", city_id: "12",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905355/Jenn_pfyyql.jpg", profile: descriptions[5])
user106 = User.create!(username: "Sarah", email: "sarah@gmail.com", fname: "Sarah", lname: "Marshall", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Sarah_pmcv2w.jpg", profile: descriptions[6])
user107 = User.create!(username: "Victor", email: "awvictor@gmail.com", fname: "Victor", lname: "Aw", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905356/Victor_ggg9zd.jpg", profile: descriptions[7])
user108 = User.create!(username: "Priya", email: "priyankachopra@gmail.com", fname: "Priya", lname: "Chopra", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905359/Priya_fd034b.jpg", profile: descriptions[8])
user109 = User.create!(username: "Alexa", email: "alexandria@gmail.com", fname: "Alexa", lname: "Bando", city_id: "12",  password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905358/Alexa_kgw4df.jpg", profile: descriptions[9])
user110 = User.create!(username: "Chelsea", email: "chealseafc@gmail.com", fname: "Chelsea", lname: "Drogba", city_id: "12", password: "123456", is_host: true, profile_pic_url: "http://res.cloudinary.com/dzixj0ktk/image/upload/v1478905351/Chelsea_wvcjts.jpg", profile: descriptions[10])
